movie_project/movie_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from movie_project import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('movieapp.urls'))
]

if settings.DEBUG:
            urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
            urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movie_project/movieapp/urls.py
from django.urls import path
from . import views
app_name = 'movieapp'

urlpatterns = [
    path('',views.index,name='index'),
    path('details/<int:movie_id>/',views.details,name='details'),
    path('add/',views.movie_add,name='movie_add'),
    path('update/<int:movie_id>/',views.update,name='update'),
    path('delete/<int:movie_id>/',views.delete,name='delete')
]

movie_project/movieapp/models.py
from django.db import models

# Create your models here.
class Movies(models.Model):
            name = models.CharField(max_length=250)
            desc = models.TextField()
            img = models.ImageField(upload_to='gallery')

movie_project/movieapp/views.py
from django.shortcuts import render, redirect

from movieapp.form import Movie_Form
from movieapp.models import Movies


# Create your views here.
def index(request):
        obj = Movies.objects.all()
        return render(request,'index.html',{'res':obj})

def details(request,movie_id):
        obj = Movies.objects.get(id=movie_id)
        return render(request,'details.html',{'res':obj})

def movie_add(request):

                if request.method == "POST":
                                name = request.POST['name']
                                img = request.FILES['img']
                                desc = request.POST['desc']

                                movie = Movies(name=name,img=img,desc=desc)
                                movie.save()
                return render(request,'add.html')


def update(request,movie_id):
            movie = Movies.objects.get(id=movie_id)
            form = Movie_Form(request.POST or None,request.FILES,instance=movie)

            if form.is_valid():
                    form.save()
                    return redirect('/')

            return render(request, 'update.html',{'form':form,'movie':movie})


def delete(request,movie_id ):
        if request.method=='POST':
                movie = Movies.objects.get(id=movie_id)
                movie.delete()
                return redirect('/')

        return render(request,'delete.html')

movie_project/templates/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Movie</title>
</head>
<body>
{% extends 'base.html' %}
{% block body %}


<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
  <input type="text" name="name" placeholder="Enter the movie name"><br>
  <input type="file" name="img"><br>
  <input type="text" name="desc" placeholder="Enter the description"><br>
  <input type="submit">

</form>
{% endblock %}
</body>
</html>

movie_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

  <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'movieapp:index' %}">MOVIES HUB</a>
  </div>
</nav>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

movie_project/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete</title>
</head>
<body>
{% extends 'base.html' %}
{% block body %}
<form method="post">
  {% csrf_token %}
    Are you sure? <br>
<input type="submit" value="Yes">

</form>
{% endblock %}
</body>
</html>

movie_project/templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
    <style>
        .center-content {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
            text-align: center;
            margin-top: -140px;
        }
    </style>
</head>
<body>
    {% extends 'base.html' %}
    {% block body %}
    <div class="center-content">


        <h2>{{res.name}}</h2><br>
        <img src="{{res.img.url}}" width="600" height="200"><br>
        {{res.desc}}<br><br>
        <a href="{% url 'movieapp:update' res.id %} " class="btn btn-primary">Update</a><br><br>
        <a href="{% url 'movieapp:delete' res.id %}" class="btn btn-primary">Delete</a>

    </div>
     {% endblock %}
</body>
</html>

movie_project/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <style>
    .custom-card {
        margin-bottom: 20px;
    }
</style>
</head>
<body>
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        {% for i in res %}
        <div class="col-md-3">
            <div class="card custom-card" style="width: 100%;height:100;">
                <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="200" height="200">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <a href="{% url 'movieapp:details' i.id %}" class="btn btn-primary">Details</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<center><a href="{% url 'movieapp:movie_add' %}" class="btn btn-primary">Add New</a> </center>
{% endblock %}
</body>
</html>

movie_project/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update</title>
</head>
<body>
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>
{% endblock %}
</body>
</html>